Update GDK to adapt current changes as of GearLock 7.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,2 +1,85 @@
 #!/usr/bin/env bash
-eval "$(printf 'H4sIAL99nl8C/+2d2ZYcR3JE3/EVOGQeERQXvEOENP9BQsH/4On59sEsAAF0LZkZttwoEC8asaurKyoiPdzNzc1ejYv/3v7+x8vtjzF+/du7pxcvn35/8erVuPbv7eX//MMP33//4sNLtl+vvejdp299663+fNm+V+1/3Y4lvN2ufQEX3u3AH975/T3/zm9/nnF9s169/r/3/15v27/+78WXvv3nzl/79+t29Ufvj8qHP3LxHV6//u3165dPlz/exz/6yR/4+IbPXvTm5U8fXvbmw/94uvjJXoyxZ4lvrq7q40+eXuz9pu6/2bP3uvRO///04ueXv7y6/IX/8ssv//y131798eXPf/75+W88/XbzVHzYsfeP+5vr+/vJj/79v55uvue1Y/DxJP3t3Y8//uctbp2qt7ff5ZPffPf3vz/tffH28Xd2/8qzT/bj7V/983e3zw/0x//+7u3v/36Hm0/Vy+/eB+NXb75/H4hffvfnC7/73//6+P/9fn0j3n99337+R59uRPO3137ww9U/cOFkXYj3P11f4PNb4oc7L/40Rry9/NW9uBQqf7q7iA+f4Yf7H/dKJL75N9683Lvfv37xwndP727s/6377ObOXbkvf9q125+t/e4B+XPNB479H093T/2n7/vl27779tv/fvP0LMTs/wA/v/7jwAe49BGufoiLn3fPPXThL7y5cMXcftmzy+g/L7y4gDfXX39mTy98E0/vL/RP//v7//DN/3xz6Ku/vgH/WsLz0P9J6vDszbZ719Ge97/5F778Gzve+NNfuvrO92/ST4/bdvey/+L9tyPvuuubOLOFO76II9/Dlc+8/4Ts+8g7T8OeN9v2frzbi919QI/syY6juevQHHh4ju3FjhR391N156Ha84YHQsrtw35o5buO9p3Tc/xrOxSDdrzvvQ+4nQlAOzfmcOy8+bm/fACOXE53N347+vkOr/1wGD4QhQ9/+DNh4O5Z2xOzdoWsg59s54KPJSbHd+/w++/4LnYdsrufbfcnu/dOJ4/k/S9vf5Q6E6aOfu5dj+rMcbq/ht0Ba3cUPBICz+T9e6/CE6n/7lC785o9+Envfhs7K5PDaz+W5++9YnbWI6d360Sttnvr9mf+O0/xzshw74Hdf2PtCl8HntWb+3L6qzuaaB5/830hZs/2fPJOewCWb7ZX91727kto6NYbPnuzbd8PL/78yB/anq3st9+urezd04Ws9JsXE1/E1MJvLUiz0M9/t7PSOyvR7qh2idv+Q357KTsXeelnm/+kzpzTUwu8+YjPrHJ/yLq95lvL0T2Zm2LN95e8Z3tF4Uh7bCeP7I4NO7ys3sGdiD6nQ5BnrQsmDNInNhapPPmS6BhMnHjZA72JcyRcxNp8sXg7fMcYHtvnP9sST2f7RlUG45kjO39OD2VJkLg7nebvuWw22SYfOaynL5sjp9lW0Zy8QrNRarOki+f3tJZObZZwpv1qMnfWF/824xMPCmribd6EGwuAazKPeC2AHX1pKb8s1EWZ+3rikEcybM31dQLesWEeUwc80CVQPNb+TZ0G7GxP5lyEOpk/J57Dc72dUnTxdjkk6d7mDCr7l9u8LVGZQw1N1gIbJ19arIDUX4Ky7JnEH8EbKgfP1RF7E9w+0uK8lBHiqx9fb2HfLaZKPr4eWO6xwpX1OiZfzfZqcLM+0+c6u6IzL0OvJtPOJO9vWLkpkcI3cmYPxqdEr+zCwUV1zVww+nVITglPhfKMg/dPl0dmoJHJHk8TuuPiiFHLBfeB3hwHefZZnY5I+QsGRKtKATWY2vd6qcTa/T3LEuw6Zb/DdzGiF2ZE7fyL1Jzh0A1tZLX3CSm19rVlLEoUjmWhyVXuVfqDmfEnZWkn28pIjWAk95puGXnHgNruHFbWFAihknc+rWPVGnDV3zZ4tLm4z36WJCxoB6dQPDnb4W4Ov80VsupglJADkBc5UrhmCHcXybXfVo1Fh1dNO8yG8VsatpphHYSkBGQUWH0/j0Sg0n0Brem3s3Fam1FsurDsunhYjekca+zkujdPXJpHEGeh716N+rBBZjCIjb4xTAu0BG9KSmcxXehLmKoYW6mtW2WAUG2ZhBlZc+SLq8Vx9/cxMeS4blK8FVdg3BNq/qAvzRcAXUxXzdeLnVqU4DZObO1Bxbos8ux+73/0jWyE8plPDo9IU40CgbveWUj2sj3piqiFXScmrKHgAg/dZQa+l22/yDxqlH/fp65akA5tXn4dv6RU+ObAjNxhv0YgQKfYBNktI+Lp6+Y3pwmGTRevcfU6go+oQ6SZgBFGmih6OgekVlXePcfRgMXx5qVVuY0vnNhARlzzUhSDCqN34KReWNecGknsinq2HggZ7kbK/2PzxvZM5EHLvIfQt1TW8ybWygItJURJP5SB3IBgZCZ2kwpxR0I0TubUA19ga46JcGzreU+t2h6PANVFKI02Cv2LqN0L2CcxQQPoE9rs7hB1729BPXzDGJRQizLRm9jMbRCO6ljIPJTTEMhDTwsYz+FUsHANLD1RkYYoDKdxTno6AGUUGOhpjcVcjwJnl6QsaW/u0Ub5N+dihR2LDDex1ZIPNDFiBuxBWvHNrKLbjtLSl/oqqOum9WtXNIjUSoXyJgf0wp0l6rB349wWbtHqqJ2z6XRgv8WKbfnsN9kpNPbz3bpOAG3q4wBooL9SzeBXzA/k8Ets2tNSwHlVm13YzMiObmjuo65glJ9geV4qRrmNI/+gm2AaHrkF5vxouLmI1Og16Dw59lLflofU/6kbMHEMt8QwZGIutuLsuXnPb5caIts6F9q2Asw/i48OnrrZ3I661IxbzM8V7OgPXwOsxFZ1SxpOrTAOIST3nCMzNX+dESFQZoTVQ6iCdvvYgpA5QLQxiRmxuk27dvVHCAwkm83+mBXsM1JOyzOPWI9RQ9R6un6v2fsEm2I3YX6HQ81JAJL4zr8Uy8jotAxsd0vmylRdNU6+bgmCTHGTgVMVtTpMGePaQ9F3F5fxQprTqOhW1sdf2jD7gbLOISiXCsTMpxfuuMy6fIrhtmAZ0NYvtOWOm+SRDfTocSXAoDsmrOp2tMboYnfgPymuOuwr3p36Fgv32Ph/aXY89DQCeQmIuoXsp3UHaMTrybjAxFzrtK12OlzE+klFTFLoXdSA96F1P21Bqjtvq0aDLYIzbFsP8KWCIRqNpdXDbSOo0ylUAHPxw2eupNCF2dPUTKUTk1CTr5WajDE1h5Rpet3PYgkjSlEw3rsczIB8ybSE0MOK2VOOcjeWsrHihzcElwaQxBBjC4AeKUF8W3gFDnQt2nnTNm1Izqqy7nGOFg5A+e1CgxXH35HzIJcc2EWN5j1RaZmxjhLZ0IPDkK5Yhv84gbqeqrVHjgYLQLjTyW8p7l68b5rqmdq0KCxfdWSxiWHPDGspAqDx8givVhnJP3IE5CsAmorB6NzFByMW5ILbF2P3cGwpwrKPxeyxEIJLms7FCSNvsZDUxWBIs9Q3k4QletOLVbFxE3oRyj66t/BKUKQJ+8DocqSFnEZ7tMWgslKq92WpNQPZycpRGtFI52NHgWmM+ozTDyLamtxAoSgj57HeTpueFcOP1Qoa8pJ2LusJBx1bgbqa3tJq7K01vgiMzvqB78DT66IU8FqRYIDUi5vNBWhRBieWR9X1LZYiRrp05jLGkhKZxyAFOMIiTNKmSIaPrNWuP88/c8uITjoWOIiyqhG3oAk4PlFr2rswo071WEu7cDCGVdcqT3AC3xRQjKhfsgCsyd++5ngJf4YxUzrL04WmI9Txl0J8vlQbbpFVOr3K4+hmyW+xMp+KaL/k0kOTadO0WLnoESYlvqmAZa9lw2P2jjvJJy41DLTQJUTnfYNUMfh3FI+1HJFxWeCKIpWFB5mS5xRQ3CmJhhluW2W6Hui8fuSl0wWTIXaT1q9oR7aK4bl4NRWo8D7l3qRjFWGfVD3ck6XodEuk6yfg7a3U2zSR1G6hnK6iokOzG/35LS/LdCEPNYua4TEC1yZ7CBcZ4nCODNqo1rrrXqJqx5zq1LapmuteJnUykAtJTHpq+Cfr13MyYE4r2X3Qa8UK37AgiCTL251cwMbZM+lR5t0oHMztSWqnc3J9PEXpOo9oGTW9s9/G3fehWJzJioKqspwDKLuxZw8VoxKTS7KinAA6LDf8UMC4MYZWAV1/kHmXIQkekgd7KelP2apN1byz5rOEbg0Hrjm4FQYyRm6CRtLnGdbYPZC+sZrKgDEA5gal2jJ62mCcFwSyRy/9LQwaIM/suC7zCnBHli8wVBdYkzTE9PqrCwYZskg/HKsVD9IUBi1U0akV7V4XqY7tx5akVVQVo5FzYxYq3/T1GlRtThGCFhhH6/Kg58CyZRuTckKeb7FpnoRLWsfwiFpxfsN+htF+MXuaZEToTujrUw1riS3SznOYwFhDC5ed9R9RL0bBXItz4TxGSWiDZ6PZ9PkmSjeLD/VBHsLiQ8LBjoch97J+F5b27MxJdz3cJlU0g3SYGMqBDnWJEhGQAnTInb49BqT2ZGkhxvaGckZ1QZs+sXLiQBe9anTMk5O5VefZOllu9sOt0+rLBbyx53qVFkW/cxffVt6yxaw7jrwUMPYbcCCMwNzRFI54onsT3udf2nrst3WCG4a2lZBFhdk6zy87ywAaDE8iR8Zf1rEKzTiTTcQiX4EKDl6W/r6IuJCGiYroWEYfbcYjnehVUnX35hJFihKSjSOexzAaSWELxoeaiqUShbb4hE9UUFiL8k1Zmo7VhvNqPbdDfogrcEu1WRMDVY3IW0wI3811WtIdoKezkpnP4o6GbNZ9pbC6AjIrVXZ1mVjdVBhsW0ury6RAkkJfMoi5NmJsqH59WGBPCy8fFueke+F4Gj3OjNBX+1sOLnSUH5/7r9HxMnf5cMQbrLZk0HraiuoxXZhcVF3F5O18/xIyomamRkaCtEojYIb62ZOQR8BtKAiyIzHZrHdbKgFLIc+iVoS0rFjrS7gB9nQjoOeudnWNRXYMmiqZk05nPQk69KKFxhTSTXIhdSxXLja9R27eULRpBEWwqubYlRTroVS8A22Ucy8t6xJp9hth35WkaGFkOlDnVfaYOp/RWMXPEWTJzFVgatuYPgKlxZ1sHRVnVd1ad4aRRoyQiRty3/xPbpoAfB1w6tIAnU5rDP6+PDW87JZelDhThdkmU1lOVG7PZab6mguaBaZViWyj1HorFJKWOXjCdrOf0dHzl97s8dSQ69WdWROiLFNJrcVDPLjNkh1mj3Tapn1qTVcv7n21phls+R3ho9zzIEChigX0rSbNr7uzkrLl8tjGWLfXKd5Y3+oHh3S5SesreCiRInnoAmnyWyyQ0MBqQ3kpJ1lrX/G5BzMyVuGYxfYUEmQmArA2PrQ4hlcz1Sel4KmRwXNo4vDTz6idlZoedvKWrn662sg75WWOYlyZcas/XG4kPNGpyvalotmL9nYgG2UfeSmhucMLr0vMHKn4slPrBVgVJToZ6lkq6dVSP6xdGZWr8Ps6vgDNgYqxUPNUe1Uaju2ZUphFpAJ4cPsTcbRVlDg9p1qFwkXGr4FwAN6VOMFBWYXKgcYiLO4/pnbrrroXOok0rg4vGzeITvKd4ExNomJf0Gn53BEuSmctoF7owPGqorOpqXC22VOEid01mWmizyNGBGJ6V5tQWe9c8LyuKBAMsowD96zKFrQ0tTgqnE+inMD0Us2hot+eMtSWzvQIHvCYfzpdSMUzy8R2pZOD34HTLML7qUP+AyJytdGe0Ao6YeeD2yfdDyMwOBsfRfK0mBb3AiawEDFfHR1wIXmDC19Ah4gThQ5ZEJQbiqJMamFKfXvbUt8xQTNGfPgylItf4tuFVGKla2WLrA+MJGyvvbNYZYDc1qavE0jQrl362Z/XkFwfcYLUyK8VgcgPx6p14slemZxQunv96czN5k9XcYAsCWkM1nB9INhLExQn1xCViJXg67ned3c74SRFgFBdFp2U8cwtcD7tNJicFxiDHWHmw59+CtMsrvVcc8uA9v41eSGFs2AKMOfPbHwOVUNhih40jT1xp6xyxZpXs4v0+50zx5ZyY+va+4rHLBHNjXIp5BwSRXuhK+l8kJyevUJC8WGq4lDcyGlFp7K7mmPm7a+hO8eq3+ctE1ZGX2VAkqhi5CJHQBdiutSAObv2e4RhbopL9aOncplEQv4SxhKgYQBzK7Ovtj1DsA/BDaiEr09Wu85x8HRnjq0qkdY3iWSf/WwLPZs19J1vsKesXBLN4NZmbs69A6a8mNlpm/FnxIQ5fGhPNUYpliiaursXeiyhtHk2S+V1GfaKJAOEy98sQrKU/7sWzASltdG8IcN2DM4b+lBOXdXMg0uyYMl0pcIfH5jbYPJlOsod3gGTvM8ZjjVVRXJjSdXb8jqE8PjGP36uXinwhNamSOQtQ0lFotMI82cL3CETDYrpMcLrjChod6OqIJcZeFRg6BE8ffYCJGJcNql+3IhyAMg8EYM85xiD13qy1qZ8/aGnE0jkdmF0whjsLzZVqd2wpBPl8frUBLNp8g0jT7pQnBp/6XAKgPfCid0iEXeAhlD9e1i+Z3IJRoKAi3M11/MVF0gca4vu4J3+wYfDNOn2gxr1By01t0vBGMJurIlVsoVQxAirg+gpYeyed7QCt/SRTFXfDZT2DPecRUGWz3bUBrZC/TROupGyJP+boX91xSHqBWkfich8G1Zw4liGQxMvpxCRHqn14bAdZClOxTzSc/exRX92QOWmDr/0bD3QazkbG5KKocN1zTFuwoPrWMKvTalXXhZRQKw4ie/SfUZdhtK0Fir10VAFzXko2aUlpW3+1aza6xusd9A9f0s+jBh1vctiEhrXIQuem9XYLp2MySywhEe16oQqrdm36el91Ef23kdtwEOjT8cCFa4te7HOI269jNiGRu1kyngfke4fg0AVzay8a11y84Dy4kp53tSfDrELGmuewGgFk03hotMlZtUYWi/c7/88LH5SNWmO/rRfLZCp2/wZXXeCzUSyOg8LJ6b9OVUHdigUgnyP4olQW67NMJjZ85/JNB3kj50BHqnHGd98HmUW07hCcR/GqeoQADgXsgzF1HKZ2xOFlokly0zJO5fUAhYybdr8efunOlCeNS/TFvm6nv59LXKtKDTM76r6UFDQiUYoOOF3QZ5U+cw1h/qshHN7DTNQIm2mJmJTi1+b6xmQPgIRp5Ew1UQ4EqmFF8Y+0moa7I6iJHZt8ae7PgklPtCLwi6kxStIZ94Ctik7Dp6JEgehTNLICb7C5o1giNFzlKMlAQBIs3Z17M1WjqkeWatGDRZnArXtiKM5pkUh55S1ian6gUbqGMJa70Grj7TnVspwxCXZVmKSTNlHgJgMMM2pc46MjU5XhAiT1GzpSBnPHlCSLRpf8raBvdgValgOd4Fr0larzzaEVLeI0OntyEtZ2QCMeIcfhksLVUeewo62md+coyvuaZMP0mO642HkhIoyfRtusTamEoIQ658sdl4pSR/qk+oqnqLaw4D2fR0YS+teijg4ss06jsA6zgGCuceSSZa6WHsUSuWWeazUbMoy1JcewcD5Vvg43qcBo44CoRULNJRwK5HY6ezI4ZU5szq1ifNdDsxravNLzjD+2LLczjD+I+r7xeU7riFEqgGzsi3QRdgIUHLlK+dW1SJ+KA9OzKiOMkp68jIWSi3kogBD8ZBDO26BwS9Vt1R4kt2K4uT8PqbAoow/Ue+yiYJFG3OzUJI+q2ADLf1b1Wzmdh4iYw3YyteqR31luZDlLrVo0MhEebvCXkRXzKRor8vyoDedFog3i8ILqUSdK3w0kdyFuqEiuE8Cu1sElwknNiIKWRe0GuiJnNOHdHasHW1dpf8qWICnvl55rCc4ievtfo6xrHoxDG2hXAcuUYyqfxsQET6QLFnlJdy5Ek6d9E4gi4wR7Km48KGy9rJf+xNmxtGaBhiieHa5Bqgpxae/gDU5zLjmk2ecLZx/zB3fNeReBsBx5CwggRt3QaSRXjkqT6xZQBwGF2TXIduPHm/MKWgU72RMpMnaximlg3MsR5pkCi7QJaf5THqg4VYvjsAJ1GqGQ0VVQkagCcQwoJ0M8DnC2ouIL5HKyCxiMF9JwjFJ3fAaaRoqysy6CE7KDqWBKN1WXj8PgL3CkoI9C2nJfiXNCXl9HZtYmveOXl5aTX18MXlPpP3ty2qnOmZh8RCM4qN18KNYiXpI9OrweiTugBw+g15kAI4Zz+LTGbDMIxVoFsMX/9C+vro6MWdgYD/1caaDe5RWd7JpKbQWnjoMpWLG48U4j0tWXZhLr2hFlhP2kppO27ZxAW1tZZU0asaR67rIey6hmWUFena2o8y2RwJSEbVZGO/OEp6Kztqh0Q3E+SJocvpwaYAtzeYLRuFE6+LPALkxnlqZGB1UZEw1Y1q3Hd1iDjJdlWYblMimbun8otv09QiD4jxuVHOGzNApA0JfeBxUX6Ge3PYCvEQUrEOWV/ItRThHIhDA8BKF7bXyQNvB2Fqb9nJgXUdfWlL/B2naakKRf0HdIT3VGiOiX49kW6tc8LViJa5EYR0zQVpwTRdcoXOoKJ7rg0KCu/9QUPWkA8tSuy+eXszBHTSNzxTLb0XiwXgIeuuaPE4DlZ1Dn9qcj21Cr3Y/jxEkJmLqX/qxLB9cqwtRLQihgxYhMfoVqX/DLuVx+nwLNccD/kflwnXVk8y1QUgkWimrpISYwqHVrlXjLydn3biRvWF6UVaVqgmjZRoV9C/ac/ULaK0vYLVcxMFlRa0JHVUcUgIC7GofDu0umkkaZ7ayOltqk6mBT/BZZX0HcTbekubLc/wHv4usyiY93keqhuszt8t9rlnBnhWEa5CjXL52gXOsVJNZ6pMw8/VL8lma6wEFQOWGewCBjwDf3OgBb/IUbeBpu791KPoWhRBJrQ9fumxMHa337Cj6znqPr0tKyrTIJsxalkneOp9fm+dc1fFmS6zCpMoHmBTBYZdGqnAuBaJUpa4xydn1wLUIyUzOpxCwlMARtVnfMoSd8xIs6dTOL8nFTthvFims1KLR4rB/GRsupHkTTRWi6C3roul1QfHZBYyXa8JTJGOCYLC/vVXj17jomBxYje0/F5F7PXPvHHtY/5I0r9w+8kbO1npQc5NJ7doXbDRnDLUw5QUW/f0Q98fIYDtW7jUKPNU5RzkvG0v8pdENsEXXyGgHrv4lCACPzMVdbq3Urj0TE1LdbWOKGOP068pKJ9eeXKbFxKB579lYyU4GOrev1iMzduRpZq/XRgMfDKwanHrauiPDMJE2A1dglbEVzFnJruHtFyqUqF5HjkZiFJ9k5f2+rJqrGWOr6Ed7nGenoX1PGIJJ6oWCMWVuY3lJCmOKPpdZmAnWu1f7ELbJQvNzF+C32e4jz953WdYh4upJ1dfHdQNwlT4nXuoXnmuKNKyj/Qq7ndUkmRj/mncvOQhvfRKNV3cjUkMInl85IKwL3dEWR15hJ2em4MD9hyiaWQEQadxmnGU/+jzSw6lMQC8n1z6389YZ5Mbo00FR9uITnT/QaZQzeb6TYvwQpeijhWWeEOXkHqySaZpEJEiOe+FqY3gC3EMNNVO+i7C6CqYuCQojkk22M72Oqiv3yuP7tiFg36ZnfA9BaqBE+0OrSGZnRkvdv2tbymvRsFavrjqLoAQ9UcKtXnYwym+Hxa91n1eo3WR04o+hbRVnUjftBvPFbqzud06hdN07FnTElqOAsaSYmvobp3di+hSRTQR6xEmBXAfFL+NYgjED9qqvd+s/KwoFZQzcCsadkcrUvQptE3M3lDYpEFzfimPaFKxQXb6ahC+4NgijbrkiV/hQ5wILNp8NNcvJ4EnotngUB1pwkddBBzvut4CoLOg2jBrm1USuCje9sG/LmHIJ6Sk6W39MjkkUbGRPbhgQCnT6acEmYAb1KcrP2aczxgbmwqmh3ubATWp0R3I8WzlCV6ssZbdsbWmpmSF+2jyGszy5dqK7nlILiTVEdFdMk2PAkUHTcjlDwJE6D6UB55FnbGrJOHZ0f57Mdg+fRcpK+AS7jdKX1JzEcyvWd9a9dc0RBPJFXus9g12fGKzvVrLLqGnWxI2//BlDiW9gZHFHwDYNqR9qnKIwSceycBq2BmGv2uE81zwZGD9U1SsRgioI0qur3zOwp5EiFVxtnU4ZcXGWeKi4a+28d0s6/zx4M1nO2NmcxC8g9na5pzxobxe8g9xB21cjVp+AIkhgdCdrySUswA07fTzT2LooC4mosXsADt234Gd1Nl0ST740OgzWEq/OXkDPf7bhjy8Lj0RRHHt6zAVNt+WcL4HxKF4TecRrqvJEmhwyEXcFkBzBqZYlDX/nSW24fZtTBFuS6+xwWJN+39yIuPgBuz8Y2ck8B8yAsNJ0/Kpzpira11TlZ+3FLKrn5VPdyLaYDWPsmqcPhBD00a1sdn88pV1IXJZgKqEOtzD1r422quR0Wr/cEcvzLGNvL0iEUsPQp0NsTfgsOJfEm4BeYgZ6TdB7Hl2i159t4UwYgCY+q4a5upCwfB/grk4/1HRFCy0au/CoGQe9DhcVfW3sLUaI60H4hCbqNtKkSkJW1VG4wg0DmrV6uFnVsXjBqOqAx5aEF5WyHgqHOU0lweJU2KftykE6BIcHqaQh1qzeJtBTCRGackYXXZRrmtVIt6wk6Qk+2gxBttqg0AqITWoDy1kYqj0i38CQtZlRYZrMMkMmZgYsgKuWr9OjS1+BdEpbegCd8kLnrclX9+hKadDKP6cCw/yL3ptnXlpVxuwgY4diiML0OIb9d8FPSEtdrTgW47koi1P3LenM6kmyMGSxuSUAUqMC0pLULqYfn9ncg0kKb97GXgvJh7aVMi78/EtrXstIIw96ZFLxa/GQ24J2F+YCH+DgUtKDzTX90kMwmoUhmBMh0QniFKEzNA1bnIqgdkDFClMWhlIejBkj8vQWfQLBTkq6HfGqk6saYt+EyzkXyErQ/cTiHXMKwCa/pDHBSKBDT/EKqYmrazNsI1TTrgwoufY1TG/UVdXsHtZTqYkY6+t1U/hSbsDOHlg8oVQfeUAGawMrNk8RCKiK3RoyJUO50xLozje5x9dJSodTlDzpYXwAysMb5HQK9OVLTuUioG1Sn5mJaKLRdtZEPSfNSNOlJ42ySwnJA8UV27dKCMk5C6ugIy+tSHE6LVyn0gkk1TfX2K4qBRjcak8+noeisuokuzknJLCKNXVykuprAHIkyYdWRuBrV53KiSnksB1P/N6/DJquQKKaCDkukGczSmxfc27S55hs7ZsoBqsbJ1LEsv2WxHN4uIH7l55JORbsJFALCxJwaYUBDr+UQfXtmME2hQxG36o567kHZsutPO4/l7b4UjJl1Si3qZNh1I2Oiw64tKKWbXB2UZVlo7YpRRvSpiNDvWLShi3kkU9Z6IUQGbx7m5JAP7OR2hUySL/aLJ/jJylPhFJ8P0j3hxNvtBngpi1G0JdHcPKWZ7IoikcI4fdUZu9sBkgU5EodurwJKggTXVjSdBZgwFkp+iDB7HSMeO896T5QCx4v6sNPkwdpdNNb6CzTmxTwPXG3sLuGdXVpPFvuzMBgExfeJNq37ZWGNGQEI3Q3W+k1sKHGtoyeOWJpcSxDj73UgD60sR5qARbMo3u4j5KN+7UcDOuPtsAlHOH/taUTFHXiiJpVZoEPY9F4M4syQ3kQqMPRXcBr4BmSKj9NWw4OdK23LBnGlRS6fwe559CL80FQX++1GgslW61inJo1AelLEgTluRa0WmtPWDhmPE9v6dZ5tsOKZMZJZBfxqsq7wpW4h4t7W0B2DgbhcMqJmziCdfX8uiT3tTn3bvIDlPUUWhi2i275+i9tka8t94iWU+uOOIFChl6Tenp2+WyjMbJaWN/Ulo5Gmy55chPPesk2CsmF8gBmaQHUhudjUhhC5m5feiJ3EVWX7oS5p3x9XJPpBucGjpfTWwYoypG5blO1/tQtEBIXw2b3wLiGWOBE7YTL6Sd0RS1xarwOoWiFLslqJi5pyXGGKrMMSRxW64uxls46asZq+OWZN2nkFudhmL1eJQmzAKpV9R8xtGEofdN2F56spMkaU+Ub+dHu3tBY1lDN2Q0BVP4XXghoHziKQ5aYKUBWOXLEMWiHOIAZhJfN+CxlTn/kJRrGAvyxk/BPEXRPqLsuMJpiArRat7CDN+NkXiA8efZXuGCnB2Ox5AG0crL6A65xfD58rQlQHnuxfaibrQr8dYwK5r4C2yWtcG6ZAbNgGvq+OjjH1w4oPd0CdFocyYQlfF9P03m54onmvmczN19ATIkHTlkQdJjNTdzZyQLALLZlE4VtaRg9Ow9PKM7pqJOVqfKAupsjrumyRP8uNftTMHA3COTN8iryM7Il7ibZpr13ZeJFZgdsaF+D3/sUNvYfSgq7uGPAU8jpG7oVCYBbklV0LA5CCugU9TO4wMpK53UgtKKNMNqd5bfF340QMEDGIe1/1p8pFj+3GOq0GyzLXy65Ii4hi8yoVBPVXK3YkdZzGcpGazKYJtm02cMMPc8ZiOmbjMqav+I8W2U3e0o2q+Zz+1Y0ttUD2Oo8gd7Hn3hA0VGI5fThEl+bvkVrd6gprhZZbVWGPQTmWn4ityBYpMaxdP2WgJVDtQeaygGWALM82EGNbROaXQsJ8gQq7Z7zOdYyyT2sOV3MjVQs06MQ518a57VsuYOuru0YiJM0KYnfZmFNgQqPK8ldA5sfHG6M1PXKGnuP9jxFjFkJNtYT6PtGTDiVRZwGsBgvchPajDLHrZLEB5qottXLla8ssiXk5axEimGtD0ocOgdQCuDRwsS1xmGpzEwhYKbGBngFrs+xMgesOo3V+5hO3dFDeppH7mhz+67Hj7H16PbURYRwr638zUwQ9BTKDZM9ttRgBRnJJThmQjzHS5ss3ait1lv6ioX344TH3ZZhdWnf8tZDILRN5x2OiRoaex9FYb+YOFL8wsV0NTDy1qrjzZFYrq3UqvwyqlGm+xbJWxQGrog3atcE1LZEPXOpfN068uQEWcMqdeFrBw0odaOBNU9jPfy86yzKvDUj9JBb+pr3q96prDPinSAk2xOxbUpcekCz+CtNTMGIYoge54qS1u4WAoXx7bIw5cjkyq+boBkvp5wbSvqTg8BarcThEt1LjFLp4BXTzGBlcuz5z1CDr4sNx5x5aZfxpGUlW7NdGhacgReKI49U9TefjJ9nalUBADfr0K5UdY2y53MzqU71mKrQLbNlI+gaUCrEjrw4kRj4aHnOISZHdkgo4XKdN1gLRhK52nwQTxSIlQgQC5zFhCPswAZVLgNgAn7ogQc+3THjIGslNZFoAylDZgpYk6yaqojPndwTjdyHdmmr6hNHMcmB0CuOIpSZBKTyBVhCV3o+xHA1teY2HddRqvHZHdkLpI0CS9cRnUYMNb2IowGJtc/DeEVCmwJ4Lmv6q1DmZNujRy3wOYt5zA1phMrTL82ncZs7uNAh0eYsXZglnETLmjCwsQbzqbGp2cRFaDAduD2NeVU1VpU/r5TY6hjd6OF4XK7sbD0C4BvGAEGddz6m0J5q7k8+XnwBkqWHSggm0h6msrEqHruEyQwt1MUMJHSpBAQbTa0Zaqtgi3U8FrIaFw4qG491jNFiPnC9Yj+F7nhJE1CleTmZV76p63TWcQ0uTM/5EgmoMoTakORgedhlLuJEuaWgXVPTj+lWqN/1BKNAchL9QKbMPqeEBTnicA0SIVVNNOPGqAFKGoMrQBtAB/BojtwEqb38tgoDkyhcfTNpMJevs52+3vF0tU9s6S1XYQcIr7mGzLq2UvIUqYREmIgI2WDk0V4R7e/CsJIGZFiRx+hQ6qORFObPL4t+S8ncEzXaLODLVtRGYppFFpvjEWR4T7JleKf7DekyZRv2x7NpMUFjMnkncAHAvCjwZGgpLR8GbcnMNfPFACDRPnZ5+jFMHeNyhFtpH/9bWS/JWFjyY7hkBo3cFpioJo3csZY5yekx/t5NZmM65DtOlqlA4zYlp6vW9P8UezP3Fc/8nexiIxsof2E2Fja65ZVWDWdnevN1GyRf8/AMDJBDZCQ9kgCRCCtMsSe2NA/SG4rJidULG0qeKCVOhkBbm7ZDjOO/ZtUHhjp1BNwOP5ylgZbyLNq9D99V2V5vGuBBhpMs7o4efjFLn2OtVKh4VlUHljIIyvYn6dwvAU0ZA03Dj2kSmXHnX/rwg3j6RxsW23JKhnCa5Dz6DT3TvtLH1dN/WBsmQx+gpUMSr9eVWjJEntIylto1UWu8gsEqw1tka7f5cuBxt5BsOQlSkUdqAec740hT6JVUIqsi8zxjOoIvXb76YuDBDdlAW/kpTxgUYKIYMs1pOhWzJTdOWDXQlINjzDarBiHy4X9CiKGtm75Adk/wgQCLEBtkVEquJ8Yhikfx/1oRl553qtBdK2YvVdmdEoT/FgrCq6D5811FWuvc5rIVHtXzQGmbOzZ5sKT14EPf92CNYIXJcGl0pyk0W/h97G6BMmQ7ZQ9K8/8h4maKAHMmytmSkZ7Kb4Mo3xPrKF1PQiOt/VtbMoYYqwhxURVUG2TLGBaAa9wKcokAin6enJdJhQ9nSDBdJGOFFEOVOZJg1qIYQWbLyREwmwWnsyU3Ah0ZYfGo6vcJYkEmo/Bq4jWPSErJiyxPn+Arxo7y6b2V686oPaUubQk+U7LTkaG9cEAhByCkY5Z6OxSr33mVTurMwaX3jLPjCpN9NSInjwnZJmqSh1BgL6D3u+vwJfpQlkKN0kBP7b4LCz/80rQtVWjXg253hNGl/JXtGkzX8zgtYClRI3seHSUWC/1Hc7b51ucDDKydavDORSn92IxkVymTH094IpAwUR/i/ATxet+ENdb7BtzUNJNpxHqN+mjy4orC9EcP+TJyQjYc6DiAzcd0VxDMVMq0IcQc9L7vLGwON9pyre2CmfiSNq6pN4gLr8n4UNezgwihL7XlNZ/4UXAu4XPnIzOaD+aq1K793NB0qLGScmDSgFt29DogV4mu/MSRjjXwFbXzTJ2ByXNek2ay+Vebew0cLQDHsCIsHA+ImHeyttjWiDsSXHl0B+TFMxRUs8PMtJcLsQrdjXZqjQ6UkmMXC/BgnbUbO2sAsi9qHlp6vE0XZfUPbEm7oSLKuWXWFj2o8nIrD56y7pkjL8XxZ+pasxYKa2M6M4B8m2KvNzqVY9PezYs7gvmir0NVXwglKEMwV/xZtcHE+VSqzZR60Wzb47QBsOa2iQ0MADTMRlnXdmf01ScQlhuokxHCYAYPljJWYjqBivJsLCZoRybAUFPb37j2lpLQvmN8ttt95mndn06gjD/MaTKImWddaU2jxXj1ABrD2gFRu15gN0EwNQ9Vh5HD+s10hekt0tkuRcWPk66sSFTESRnllm/RYREUGQD/2ImQbJU5FR/UKcA3LqCxAp+M5XXlB5S+igFzOQS6xhCJQxe9lCvn9rZtt+qzPrLXdZLUYfLqGWUFq7YfNFU4geSuKKjZoznUFjnKICZIbHpoVLU0ru+0owKSkQsbQjaFkXsNDIzsvgmfw4rCQFRUjwBNLKPcY1dE7GdJjqywe5/GiCHpfuMWWpdmiXUsWHio84L4DzZGVTCrc6LmiSog3AFS5WKzAAeiaXJrHd10K6fTS7dw0mKRE7uaV748GIEmnshvXnz/zfcv/gHlJLSZlocGAA=='|base64 -d|gunzip -c)"
+
+# FIXME: This was poorly coded in the past on rush.
+
+# Check Android env
+if test -z "$GEARLOCK_V"; then
+	BD="$(dirname "$(readlink -f "$0")")"
+	export GTMP="$BD/cache" \
+		WORKDIR="$BD/workdir" \
+		GCOMM="gearlock" \
+		GRLOAD="$BD/gearload" \
+		PS3="$(echo -e "\nEnter a number >> ")" 
+	mkdir -p "$GTMP" "$GRLOAD"
+	PATH="$BD/bin:$PATH"
+	! chmod -R 777 "$BD/bin" > /dev/null 2>&1 \
+		&& echo "Failed to get execution permissions on 'bin/garc'" && exit 1
+fi
+
+
+function main(){
+	! curl --output /dev/null --silent --fail -r 0-0 "https://www.google.com" \
+		&& echo -e "Your internet is down." && exit 1
+		
+	echo -e "\n+ Downloading $1 ..." && {
+		! curl -LkSs "https://api.github.com/repos/AXIM0S/${1}/tarball" -o "$GTMP/${1}.tar.gz" \
+			&& echo -e "Failed to download skeleton package, please try again" && exit 1
+	}
+	
+	echo -e "\n+ Setting up $1 ...\n" && {
+		test -e "$WORKDIR" && read -rn1 -p ' -- [!!!] Warning, workdir already exists, remove ? [Y/n] ' c && test "${c,,}" == "y" && rm -r "$WORKDIR"
+		mkdir -p "$WORKDIR"
+		tar --strip-components=1 -C "$WORKDIR" -xf "$GTMP/${1}.tar.gz"
+		find "$WORKDIR" -name ".keep" -exec rm {} +
+		chmod -R 755 "$WORKDIR"
+	}
+	
+	echo -e "\n+ Browse to $WORKDIR"
+	echo -e "\n+ If you havent read the documentation yet then visit https://supreme-gamers.com/gearlock"
+	test -z "$ME" && echo -e "\n\n++ Run ./build to make your extension/package once it's ready"
+	:
+}
+
+wizard_run(){
+	echo -e "~ Choose what kind of Custom Package you want to work with ...\n"
+	echo -e "~ You may select the *kernel/mesa-specific package if you want a pre-configured kernel/mesa installer engine\n"
+	echo -e "~ You can use the *core-package for building something complex like an ${BGREEN}Extension${RC} or for ${YELLOW}boot-executables${RC} or anything!\n"
+
+	select opt in "Kernel Package" "Mesa Package" "Custom Core Package" "Exit"; do
+		if ! echo "$opt" | grep -q 'Exit'; then
+			main "gearlock-$(echo "${opt,,}" | sed -e 's|custom ||' -e 's| package||')-pkg"
+			break
+		else
+			exit 0
+		fi
+	done
+}
+
+
+show_help(){
+echo -e "
+GearLock Development Kit
+\$ Command Line Options: ./${0##*/} <option>
+
+
+    --gearlock-kernel-pkg           Ready to use kernel package
+    
+    --gearlock-mesa-pkg             Ready to use mesa package
+    
+    --gearlock-core-pkg             The core package for extensive use
+    
+    --help, -h                      Print this help message
+    "
+}
+
+if test -z "$1"; then
+	wizard_run
+else
+	case "$1" in
+		--gearlock-kernel-pkg) main "${1#--}" ;;
+		--gearlock-mesa-pkg) main "${1#--}" ;;
+		--gearlock-core-pkg) main "${1#--}" ;;
+		--help|-h) show_help ;;
+		*) echo -e "${0##*/}: unknown option: "$* && show_help ;;
+	esac
+fi
